In [ ]:
import numpy as np
import torch
from torch import nn
import matplotlib.pyplot as plt

In [ ]:
torch.manual_seed(42)
inputs = torch.randn(1000,3)
values = [[5,10,15],[20,25,30]]
weights = torch.tensor(values)
weights = weights.float()
bias = torch.tensor([60,90])
bias = bias.float()
bias

In [ ]:
targets = inputs @ weights.t() + bias
targets[:10], inputs[:10]

(tensor([[ 98.0182, 192.7419],
         [ 37.7384,  27.8137],
         [ 32.4560,  26.4579],
         [ 43.2647,  71.0543],
         [ 39.2337,  38.3915],
         [ 77.8414, 141.5189],
         [ 50.5369,  68.2979],
         [ 98.6089, 182.0050],
         [ 88.5168, 166.3071],
         [ 64.9838, 112.1569]]),
 tensor([[ 1.9269,  1.4873,  0.9007],
         [-2.1055,  0.6784, -1.2345],
         [-0.0431, -1.6047, -0.7521],
         [ 1.6487, -0.3925, -1.4036],
         [-0.7279, -0.5594, -0.7688],
         [ 0.7624,  1.6423, -0.1596],
         [-0.4974,  0.4396, -0.7581],
         [ 1.0783,  0.8008,  1.6806],
         [ 1.2791,  1.2964,  0.6105],
         [ 1.3347, -0.2316,  0.0418]]))

In [ ]:
train_split = int(0.8 * len(inputs))
input_train , target_train = inputs[:train_split], targets[:train_split]
input_test, target_test = inputs[train_split:], targets[train_split:]


In [ ]:
# Data Visualization will happen later


In [ ]:
class LinearRegressionModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.weights = nn.Parameter(torch.randn(size=(2,3), dtype=torch.float), requires_grad=True)
    self.bias = nn.Parameter(torch.randn(2, dtype=torch.float), requires_grad=True)
  def forward(self, x):
    return x @ self.weights.t() + self.bias


In [ ]:
# Set random seed since nn.Parameters are randomly generated
torch.manual_seed(42)

# Create an instance of the model
model_2 = LinearRegressionModel()

# check the nn.parameters that we created randomly
list(model_2.parameters())

[Parameter containing:
 tensor([[ 0.3367,  0.1288,  0.2345],
         [ 0.2303, -1.1229, -0.1863]], requires_grad=True),
 Parameter containing:
 tensor([ 2.2082, -0.6380], requires_grad=True)]

In [ ]:
# list named parameters
model_2.state_dict()

OrderedDict([('weights',
              tensor([[ 0.3367,  0.1288,  0.2345],
                      [ 0.2303, -1.1229, -0.1863]])),
             ('bias', tensor([ 2.2082, -0.6380]))])

In [ ]:
# make predictions with the model
with torch.inference_mode():
  target_preds = model_2(input_test)

In [ ]:
# check on the target_test values

In [ ]:
# check the predictions
print(f"Number of testing samples :{len(target_test)}")
print(f"Number of predictions made: {len(target_preds)}")
print(f"Predicted values: \n {target_preds}")

In [ ]:
# plot predictions

In [ ]:
list(model_2.parameters())

[Parameter containing:
 tensor([[ 0.3367,  0.1288,  0.2345],
         [ 0.2303, -1.1229, -0.1863]], requires_grad=True),
 Parameter containing:
 tensor([ 2.2082, -0.6380], requires_grad=True)]

In [ ]:
loss_fn = nn.L1Loss() # MAE is the same as L1Loss

# create an optimizer
optimizer = torch.optim.SGD(params=model_2.parameters(), lr=0.01)

In [ ]:
torch.manual_seed(42)

# set the number of epochs (How many times the model will pass the training data)
epochs = 100000

# create empty loss lists to track values
train_loss_values = []
test_loss_values = []
epoch_count = []

for epoch in range(epochs):
  ### Training

  # put model in training mode
  model_2.train()

  # forward pass on the training data using the forward function
  target_preds = model_2(input_train)

  # calculate the loss
  loss = loss_fn(target_preds, target_train)

  # Zerograd of the optimizer
  optimizer.zero_grad()

  # Loss Backwards
  loss.backward()

  # progress the optimizer
  optimizer.step()

  ## Testing

  # put the model in evaluation mode
  model_2.eval()

  with torch.inference_mode():
    #1 forward pass on the test data
    test_preds = model_2(input_test)

    #2 Calculate the loss on test data
    test_loss = loss_fn(test_preds, target_test.type(torch.float))  # predictions come in torch.float datatype, so comparisons need to be done with tensors of the same type

    # print out what's happening
    if epoch % 1000== 0:
      epoch_count.append(epoch)
      train_loss_values.append(loss.detach().numpy())
      test_loss_values.append(test_loss.detach().numpy())
      print(f"Epoch: {epoch} | MAE Train Loss : {loss} | MAE Test Loss: {test_loss}")





Epoch: 0 | MAE Train Loss : 30.067737579345703 | MAE Test Loss: 30.195606231689453
Epoch: 1000 | MAE Train Loss : 26.3846378326416 | MAE Test Loss: 26.482925415039062
Epoch: 2000 | MAE Train Loss : 22.79364585876465 | MAE Test Loss: 22.852783203125
Epoch: 3000 | MAE Train Loss : 19.281875610351562 | MAE Test Loss: 19.29962921142578
Epoch: 4000 | MAE Train Loss : 16.4222469329834 | MAE Test Loss: 16.435205459594727
Epoch: 5000 | MAE Train Loss : 14.614543914794922 | MAE Test Loss: 14.62436294555664
Epoch: 6000 | MAE Train Loss : 12.81957721710205 | MAE Test Loss: 12.830827713012695
Epoch: 7000 | MAE Train Loss : 11.040485382080078 | MAE Test Loss: 11.056778907775879
Epoch: 8000 | MAE Train Loss : 9.287463188171387 | MAE Test Loss: 9.310379981994629
Epoch: 9000 | MAE Train Loss : 7.5503644943237305 | MAE Test Loss: 7.587217807769775
Epoch: 10000 | MAE Train Loss : 5.841482639312744 | MAE Test Loss: 5.886124134063721
Epoch: 11000 | MAE Train Loss : 4.155818939208984 | MAE Test Loss: 4.198

In [ ]:
# Plot the loss Curves


In [ ]:
# Find our Model's learned parameters
print("The model learned the following values for weights and bias:")
print(model_2.state_dict())
print("\nAnd the original values for weights and bias are:")
print(f"weights: {weights}, bias: {bias}")

The model learned the following values for weights and bias:
OrderedDict([('weights', tensor([[ 5.0000, 10.0001, 14.9999],
        [20.0010, 25.0007, 30.0002]])), ('bias', tensor([60.0021, 90.0005]))])

And the original values for weights and bias are:
weights: tensor([[ 5., 10., 15.],
        [20., 25., 30.]]), bias: tensor([60., 90.])
